### PR TITLE
Preserve data in browser

### PR DESCRIPTION
**Pull request by Fsher07**
-Form input datas stored at localstorage
-Form prefilled when refreshing or open a new window

### CODE REVIEW

**Review by Deepakdanger — CHANGES_REQUESTED** [review]
Hi @Fsher07, 

Good job so far! 👏
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
- [ ] In README File, In `Getting started` section. There should be neccesary code to run the project locally. For ex:-
```
git clone https://github.com/Fsher07/Fsher07.github.io.git
cd Fsher07.github.io
```
- [ ] Kindly update your live link. It is good practice to update the live link.
- [ ] Kindly add the Javascript linter also & make sure it passes in GitHub checks.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Fsher07** [comment]
Hi @Deepakdanger , thank you for your feedback. Actually, I have javaScript linter and I checked it. Also in my previous PR I used same linter and there was no problem. I will update live link and getting started section^^

**Comment by Deepakdanger** [comment]
@Fsher07 , Check below image, Here only 3 checks are passed, there should be `ESlint` passed. Please check your linter file from this link.The [JavaScript](https://github.com/microverseinc/linters-config/tree/master/javascript) and [HTML&CSS](https://github.com/microverseinc/linters-config/tree/master/html-css) linters is set correctly project repository.
dfdfsdf

**Comment by Fsher07** [comment]
@Deepakdanger, I already followed those steps and I have .eslintrc.json file in my folder. I also check my code with npx eslint. command. But I couldn't make it to take tests in GitHub.

**Review by AnselemOdims — APPROVED** [review]
### Hi  @Fsher07 🙋‍♀️, 
Good job in making the required changes 👏 

# STATUS APPROVED ✔
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Use the tag @AnselemOdims for a quicker reply


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
